[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   server role = standalone server
   security = user
   passdb backend = tdbsam
   map to guest = never
   guest account = nobody
   usershare allow guests = no

   disable netbios = yes
   smb ports = 445
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file

   # Agar share yang tidak boleh diakses user tidak tampil saat smbclient -L.
   access based share enum = yes

# Template audit untuk semua share.
# Log mentah akan masuk syslog local7, lalu diproses audit_parser.py
# menjadi format soal di /logs/libraryit.log.

[ebooks]
   comment = Koleksi e-book LibraryIT
   path = /libraryit/ebooks
   browseable = yes
   guest ok = no
   read only = yes
   valid users = @staff @readonly
   write list = @staff
   force group = staff
   create mask = 0664
   directory mask = 0775

   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = connect pwrite write mkdirat renameat unlinkat pread read
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[papers]
   comment = Koleksi paper LibraryIT
   path = /libraryit/papers
   browseable = yes
   guest ok = no
   read only = yes
   valid users = @staff @readonly
   write list = @staff
   force group = staff
   create mask = 0664
   directory mask = 0775

   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = connect pwrite write mkdirat renameat unlinkat pread read
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[sourcecode]
   comment = Koleksi source code LibraryIT
   path = /libraryit/sourcecode
   browseable = yes
   guest ok = no
   read only = yes
   valid users = @staff
   force group = staff
   create mask = 0640
   directory mask = 0750

   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = connect pread read
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[docs]
   comment = Dokumentasi LibraryIT
   path = /libraryit/docs
   browseable = yes
   guest ok = no
   read only = yes
   valid users = @staff @readonly
   write list = librarian
   force group = staff
   create mask = 0664
   directory mask = 0775

   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = connect pwrite write mkdirat renameat unlinkat pread read
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE
